### PR TITLE
loader: clear txns and dmls buffer to free memory

### LINKED ISSUE #1087: memory leak in drainer after a big transaction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
upstream execute a big transaction(e.g. delete many rows) daily(e.g. at 12:00 a.m.)

2. What did you expect to see?
drainer memory reduce after the transaction was replicated.

3. What did you see instead?
drainer memory didn't reduce.

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)
v4.0.14

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
close #1087 

### What is changed and how it works?
nil the txns and dmls slice so golang can gc the big txn

Related changes

 - Need to be included in the release note

### Release note

 - fix drainer memory leak after a big transaction

### CODE REVIEW

File: pkg/loader/load.go [hunk 1]
```diff
@@ -739,8 +739,8 @@ func (b *batchManager) execAccumulatedDMLs() (err error) {
 	if b.fDMLsSuccessCallback != nil {
 		b.fDMLsSuccessCallback(b.txns...)
 	}
-	b.txns = b.txns[:0]
-	b.dmls = b.dmls[:0]
+	b.txns = nil
```
Comment (lance6716) [inline pkg/loader/load.go:742]: maybe we should assign nil to each element to release reference before `b.txns = b.txns[:0]`

Comment (lichunzhu) [reply pkg/loader/load.go:742]: https://stackoverflow.com/questions/50732829/will-gc-collect-the-objects-while-the-array-set-to-nil-in-golang

**Review by lance6716 — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]

**Comment by lichunzhu** [comment]
https://github.com/pingcap/tidb-binlog/blob/9f16f6e/pkg/loader/load.go#L477
Do we need to change this too?

**Comment by GMHDBJD** [comment]
> https://github.com/pingcap/tidb-binlog/blob/9f16f6e/pkg/loader/load.go#L477 Do we need to change this too?

Will byHash be GC after the function return?
