### PR TITLE
drainer: exit with non-zero code for some errors

### LINKED ISSUE #1010: open relay log feature, drainer down because of add index timeout in downstream
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
1. open relay log feature in a master-slave env
2. add 10000000 record in table in upstream
3. add index for this table in upstream

2. What did you expect to see?
data in downstream is the same as it in upstream
nodes status is normal

3. What did you see instead?
drainer status turn to down
[2020/11/13 22:26:10.316 +08:00] [ERROR] [server.go:289] ["syncer exited abnormal"] [error="invalid connection"] [errorVerbose="invalid connection\ngithub.com/pingcap/errors.AddStack\n\t/home/jenkins/agent/workspace/build_tidb_binlog_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/home/jenkins/agent/workspace/build_tidb_binlog_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15\ngithub.com/pingcap/tidb-binlog/pkg/loader.(*loaderImpl).execDDL\n\t/home/jenkins/agent/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pkg/loader/load.go:431\ngithub.com/pingcap/tidb-binlog/pkg/loader.(*batchManager).execDDL\n\t/home/jenkins/agent/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pkg/loader/load.go:748\ngithub.com/pingcap/tidb-binlog/pkg/loader.(*batchManager).put\n\t/home/jenkins/agent/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pkg/loader/load.go:770\ngithub.com/pingcap/tidb-binlog/pkg/loader.(*loaderImpl).Run\n\t/home/jenkins/agent/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pkg/loader/load.go:602\ngithub.com/pingcap/tidb-binlog/drainer/sync.(*MysqlSyncer).run\n\t/home/jenkins/agent/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/drainer/sync/mysql.go:237\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"]
[2020/11/13 22:26:10.316 +08:00] [INFO] [util.go:72] [Exit] [name=syncer]
[2020/11/13 22:26:10.316 +08:00] [INFO] [server.go:451] ["begin to close drainer server"]
[2020/11/13 22:26:10.324 +08:00] [INFO] [server.go:416] ["has already update status"] [id=172.16.4.134:8249]
[2020/11/13 22:26:10.324 +08:00] [INFO] [server.go:455] ["commit status done"]
[2020/11/13 22:26:10.324 +08:00] [INFO] [util.go:72] [Exit] [name=heartbeat]
[2020/11/13 22:26:10.324 +08:00] [INFO] [collector.go:135] ["publishBinlogs quit"]
[2020/11/13 22:26:10.324 +08:00] [INFO] [pump.go:77] ["pump is closing"] [id=172.16.4.184:8250]
[2020/11/13 22:26:10.324 +08:00] [INFO] [pump.go:77] ["pump is closing"] [id=172.16.4.116:8250]
[2020/11/13 22:26:10.324 +08:00] [INFO] [pump.go:77] ["pump is closing"] [id=172.16.4.134:8250]
[2020/11/13 22:26:10.324 +08:00] [INFO] [util.go:72] [Exit] [name=collect]
[2020/11/13 22:26:10.325 +08:00] [INFO] [main.go:73] ["drainer exit"]
~

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)

v4.0.8

### LINKED ISSUE #1011: open relay log param, binlog has been synced to downstream, pd stopped，drainer process didn't exit
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
1. m-s env, open relay log param
2. binlog has been synced to downstream
3. stop pd nodes
4. drainer process didn't exited

2. What did you expect to see?

drainer exited for heartbeat broken with PD

3. What did you see instead?
process still exist

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)
["Release Version"=v4.0.8]

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

fix #1010 

fix #1011 

### What is changed and how it works?

exit with non-zero code if `s.syncer.Start` or `s.heartbeat` returned errors.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
   - for #1010 , insert duplicate entry in downstream directly to simulate `s.syncer.Start` failed
   - for #1011, kill upstream PD

Code changes

 - Has exported function/method change

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### Release note
- exit drainer process with non-zero code if upstream PD is down or apply DDL/DML to downstream failed

### CODE REVIEW

**Comment by csuzhangxc** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

File: drainer/server.go [hunk 1]
```diff
@@ -287,6 +292,7 @@ func (s *Server) Start() error {
 		defer func() { go s.Close() }()
```
Comment (july2993) [inline drainer/server.go:292]: there's race here and 
```
	go func() {
		err2 := <-bs.Errors()
		log.Error("drainer reported error", zap.Error(err2))
		bs.Close()
		os.Exit(2)
	}()
```

both close server and if later one gets called later it may return and exit before the first one finishes.

Comment (july2993) [reply drainer/server.go:292]: how about just make `Server.Start()` return the the error of `s.syncer.Start()` if it returns error

File: drainer/server.go [hunk 2]
```diff
@@ -269,6 +273,7 @@ func (s *Server) Start() error {
 	go func() {
 		for err := range errc {
 			log.Error("send heart failed", zap.Error(err))
+			s.reportError(err)
```
Comment (july2993) [inline drainer/server.go:276]: it seems no need to quit once it failed to update the statue here, the replication can still work.
how about only failed and quit it failed to update status for a long time?

**Comment by csuzhangxc** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by csuzhangxc** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by csuzhangxc** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by csuzhangxc** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by csuzhangxc** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by csuzhangxc** [comment]
@july2993 PTAL again

**Review by july2993 — APPROVED** [review]

**Comment by csuzhangxc** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0
